// products.js
export const products = [
    {
      name: "Laptop Pro 15",
      type: "Electronics",
      price: 1200.00,
      isFavorite: true,
      isDeleted: false,
      supplierId: 103, 
    },
    {
      name: "Eco-friendly Water Bottle",
      type: "Household",
      price: 25.00,
      isFavorite: false,
      isDeleted: false,
      supplierId: 104, 
    },
    {
      name: "Solar Panel Kit",
      type: "Energy",
      price: 800.00,
      isFavorite: false,
      isDeleted: false,
      supplierId: 105,
    },
    {
      name: "Water",
      type: "Beverage",
      price: 20.00,
      isFavorite: true,
      isDeleted: false,
      supplierId: 106, 
    },
    {
      name: "Beer",
      type: "Beverage",
      price: 20.00,
      isFavorite: false,
      isDeleted: false,
      supplierId: 106, 
    },
    {
      name: "Chicken",
      type: "Meat",
      price: 300.00,
      isFavorite: false,
      isDeleted: false,
      supplierId: 107, 
    },
    {
      name: "Beef",
      type: "Meat",
      price: 500.00,
      isFavorite: false,
      isDeleted: false,
      supplierId: 107, 
    },
    {
      name: "Chicken",
      type: "Meat",
      price: 400.00,
      isFavorite: false,
      isDeleted: false,
      supplierId: 108, 
    },
    {
      name: "Fish",
      type: "Meat",
      price: 600.00,
      isFavorite: false,
      isDeleted: false,
      supplierId: 108, 
    },
  ];
