export const products = [
  {
    name: "Water",
    type: "Beverage",
    price: 20.0,
    isFavorite: true,
    isDeleted: false,
    supplierName: "Supplier A", // Link to the supplier
  },
  {
    name: "Beer",
    type: "Beverage",
    price: 20.0,
    isFavorite: false,
    isDeleted: false,
    supplierName: "Supplier B",
  },
  {
    name: "Chicken",
    type: "Meat",
    price: 300.0,
    isFavorite: false,
    isDeleted: false,
    supplierName: "Supplier C",
  },
  {
    name: "Beef",
    type: "Meat",
    price: 500.0,
    isFavorite: false,
    isDeleted: false,
    supplierName: "Supplier A",
  },
  {
    name: "Chicken",
    type: "Meat",
    price: 400.0,
    isFavorite: false,
    isDeleted: false,
    supplierName: "Supplier B",
  },
  {
    name: "Fish",
    type: "Meat",
    price: 600.0,
    isFavorite: false,
    isDeleted: false,
    supplierName: "Supplier C",
  },
];
