import { SidebarProvider } from '../app/context/SidebarContext';
import { Poppins } from "next/font/google";
import "./globals.css";
import { SupplierProvider } from './context/SuppliersContext';
import { ProductProvider } from './context/ProductsContext';
import { SnackbarProvider } from './context/SnackbarContext';
import { LocationProvider } from './context/LocationContext'

const poppins_init = Poppins({
  subsets: ['latin'],
  variable: "--font-poppins",
  weight: ['100','200','300','400', '500', '600', '700', '800'],
});


export const metadata = {
  title: "VendorView",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <body className={poppins_init.variable}>
        <SidebarProvider>
          <SnackbarProvider>
            <SupplierProvider>
              <ProductProvider>
                <LocationProvider>
                  {children}
                </LocationProvider>
              </ProductProvider>
            </SupplierProvider>
          </SnackbarProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
