import { SidebarProvider } from '../app/context/SidebarContext';
import { Poppins } from "next/font/google";
import "./globals.css";
import { SupplierProvider } from './context/SuppliersContext';
import { ProductProvider } from './context/ProductsContext';

const poppins_init = Poppins({
  subsets: ['latin'],
  variable: "--font-poppins",
  weight: ['100','200','300','400', '500', '600', '700', '800'],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins_init.variable}>
        <SidebarProvider>
        <SupplierProvider>
          <ProductProvider>
            
              { children }
  
            </ProductProvider>
        </SupplierProvider>
        </SidebarProvider>


      </body>
    </html>
  );
}
